Repository mobxjs/mobx-state-tree, pull requests merged in 2021-01, with the labels that each got.

#1610 Add missing type definitions for onInvalidated in safeReference
  packages/mobx-state-tree/src/types/utility-types/reference.ts
Labels: next-release

#1584 isPlainObject() to support objects from another window
  packages/mobx-state-tree/src/utils.ts
Labels: breaking change, next-release

#1581 Snapshot processor is assignable from fix
  packages/mobx-state-tree/__tests__/core/snapshotProcessor.test.ts
  packages/mobx-state-tree/src/types/utility-types/snapshotProcessor.ts
Labels: breaking change, next-release

#1522 applyPatch replace root of store if path is empty
  packages/mobx-state-tree/__tests__/core/action.test.ts
  packages/mobx-state-tree/src/core/node/object-node.ts
Labels: breaking change, next-release

#1609 Update the intro on the README and add a code example section
  README.md
Labels: docs or examples

#1593 Fix example packages
  packages/mst-example-boxes/README.md
  packages/mst-example-boxes/webpack.config.js
  packages/mst-example-todomvc/package.json
  packages/mst-example-todomvc/src/components/Footer.js
  packages/mst-example-todomvc/src/components/Header.js
  packages/mst-example-todomvc/src/components/MainSection.js
  packages/mst-example-todomvc/src/components/TodoItem.js
  packages/mst-example-todomvc/src/components/TodoTextInput.js
  packages/mst-example-todomvc/src/index.js
  packages/mst-example-todomvc/src/models/todos.js
  packages/mst-example-todomvc/yarn.lock
Labels: question
